/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ususstudios.torgrays_datagen;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
